site_name: GitOps Tools for ArgoCD
site_description: A vscode extension that connects with ArgoCD. Manage Clusters, Repositories and Applications without leaving VSCode. Additionally create reusable templates for applications and fast track the dev process, and much more.
site_author: Harsh Paliwal
site_url: https://paliwal999harsh.github.io/vscode-argocd/

# strict: true

copyright: Copyright Â© 2025 Harsh Paliwal

repo_url: https://github.com/paliwal999harsh/vscode-argocd
repo_name: vscode-argocd

theme:
  name: material
  palette:
    - scheme: default
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: deep orange
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - search.highlight
    - search.suggest
    - content.code.annotate
    - content.code.copy
nav:
  - Home:
      - Overview: index.md
      - Getting Started: getting-started.md
      - Features: features.md
  - Commands:
      - Overview: commands/index.md
      - Cluster Commands:
          - Overview: commands/cluster/index.md
          - Add Cluster: commands/cluster/add-cluster.md
          - Refresh Clusters: commands/cluster/refresh-clusters.md
          - Delete Cluster: commands/cluster/delete-cluster.md
      - Repository Commands:
          - Overview: commands/repository/index.md
          - Add Repository: commands/repository/add-repository.md
          - Copy Repository URL: commands/repository/copy-repository-url.md
          - Create Application from Repository: commands/repository/create-application-from-repository.md
          - Refresh Repositories: commands/repository/refresh-repositories.md
          - Delete Repository: commands/repository/delete-repository.md
      - Application Commands:
          - Overview: commands/application/index.md
          - Create Application: commands/application/create-application.md
          - Sync Application: commands/application/sync-application.md
          - Refresh Application: commands/application/refresh-application.md
          - View Application Manifests: commands/application/view-application-manifests.md
          - View Application History: commands/application/view-application-history.md
          - Rollback Application: commands/application/rollback-application.md
          - Refresh All Applications: commands/application/refresh-all-applications.md
          - Edit Application: commands/application/edit-application.md
          - Delete Application: commands/application/delete-application.md
      - Template Commands:
          - Overview: commands/template/index.md
          - Add Template: commands/template/add-template.md
          - Edit Template: commands/template/edit-template.md
          - Refresh Templates: commands/template/refresh-templates.md
          - Create Application from Template: commands/template/create-application-from-template.md
          - Delete Template: commands/template/delete-template.md
      - Code Lens Commands:
          - Overview: commands/codelens/index.md
          - ArgoCD Yaml Detection: commands/codelens/argocd-yaml-detection.md
          - Create Application: commands/codelens/create-application.md
          - Create Template: commands/codelens/create-template.md
      - Connections Commands:
          - Overview: commands/connections/index.md
          - Add Connection: commands/connections/add-connection.md
          - List Connections: commands/connections/list-connections.md
          - Switch Connection: commands/connections/switch-connection.md
          - Edit Connection: commands/connections/edit-connection.md
          - Delete Connection: commands/connections/delete-connection.md
      - Show Output Command: commands/show-output.md
      - Troubleshoot: troubleshoot.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  # - pymdownx.superfences
  # - pymdownx.tabbed

plugins:
  - search
  - social
  - git-revision-date-localized:
      type: date

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/paliwal99harsh
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/paliwal999harsh
    - icon: fontawesome/solid/paper-plane
      link: mailto:harshpaliwal.developer+vsargocd@gmail.com
  generator: false
